# server配置
server:
  port: 8050
# SpringBoot配置
spring:
  application:
    name: MessageBoard
  datasource:
    url: jdbc:mysql://192.168.0.105:3306/messageboard?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小、最小、最大连接数
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 监控后台账号和密码
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
      # 配置 StatFilter
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  # thymeleaf模板引擎配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    
# Mybatis-plus配置
mybatis-plus:  mapper-locations:  - classpath:mapper/*.xml
  type-aliases-package: com.qsd.messageboard.po
  
# Swagger配置
#swagger:#  enabled: true
#  title: 留言板
#  description: java程序员进阶之路
#  version: 1.5
#  license: Apache License, Version 2.0
#  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
#  terms-of-service-url: https://github.com/q2316367743/MessageBoard
#  contact:#    name: 乔盛达
#    email: m17762618644@163.com
#    url: https://github.com/q2316367743
    
